---
# configure for production

- name: Make sure the base directory exsists
  file: path={{app_base_path}} state=directory

- name: Make sure the front end code is on the box
  synchronize: src=../../client.prod dest={{app_base_path}}

- name: Make sure the server code is on the box
  synchronize: src=../../server dest={{app_base_path}}

- name: Make sure the config code is on the box
  synchronize: src=../../config/client-info.json dest={{app_base_path}}/config/client-info.json

- name: Make sure a project config directory exists
  file: path={{app_base_path}}/config state=directory
